### ISSUE TITLE
What is starlite?

### ISSUE THREAD

**Issue by jounathaen** [mox-mox/vim-localsearch#1]
The README out of sudden mentions vim-starlite.
Seems to be another plugin that does mostly the same?

The README could explain it a bit more.

Cheers!

**Comment by mox-mox** [comment]
Starlite is another plugin of mine. They started out as one plugin which I later divided into two. In the process I obviously forgot to change the name in the readme. It is corrected now.
Btw: Thanks for the feedback!

**Comment by jounathaen** [comment]
The README still contains the line:
`Copy the mappings in :help starlite-recommended into your .vimrc/init.vim`
:wink:

**Comment by mox-mox** [comment]
Ok, a bit embarrassing, since it was exactly the next line. Fixed...
